StartMovie.delete_all

m1 = StartMovie.create(:title => "Inception", :year => "2010")
m2 = StartMovie.create(:title => "Fast Five", :year => "2011")
m3 = StartMovie.create(:title => "The Departed", :year => "2006")
m4 = StartMovie.create(:title => "The Breakfast Club", :year => "1985")
m5 = StartMovie.create(:title => "Knocked Up", :year => "2007")
m6 = StartMovie.create(:title => "Love Actually", :year => "2003")
m7 = StartMovie.create(:title => "Ocean's Eleven", :year => "2001")
m8 = StartMovie.create(:title => "The Matrix", :year => "1999")
m9 = StartMovie.create(:title => "Dodgeball", :year => "2004")
m10 = StartMovie.create(:title => "Bridesmaids", :year => "2011")
m11 = StartMovie.create(:title => "The Usual Suspects", :year => "1995")
m12 = StartMovie.create(:title => "Pulp Fiction", :year => "1994")
m13 = StartMovie.create(:title => "Inglorious Basterds", :year => "2009")
m14 = StartMovie.create(:title => "The Avengers", :year => "2012")
m15 = StartMovie.create(:title => "Magic Mike", :year => "2012")
m16 = StartMovie.create(:title => "Superbad", :year => "2007")
m17 = StartMovie.create(:title => "Titanic", :year => "1997")
m18 = StartMovie.create(:title => "Saving Private Ryan", :year => "1998")
m19 = StartMovie.create(:title => "Space Cowboys", :year => "2000")
m20 = StartMovie.create(:title => "Lincoln", :year => "2012")
